import { requireAdmin } from "@/lib/supabase/require-admin";
import { getCatalogAiReadiness } from "@/services/catalog-ai-service";
import { createCatalogSupplierAction, processCatalogAiAction, reviewCatalogAiAction, runTestCatalogSyncAction } from "./actions";

type RecordValue = Record<string, unknown>;
export default async function CatalogControlPage() {
  const { supabase } = await requireAdmin();
  const [suppliers, products, results] = await Promise.all([
    supabase.from("suppliers").select("id,name,status,feed_type,last_sync_at").order("created_at", { ascending: false }).limit(20),
    supabase.from("catalog_products").select("id,title,status,price,cost,margin,stock,score,missing_fields,supplier_products(original_title,original_description,brand,category,image_urls,product_url)").order("updated_at", { ascending: false }).limit(50),
    supabase.from("catalog_ai_results").select("id,catalog_product_id,output,quality_score,recommendation,status,reasons:review_reason,created_at").order("created_at", { ascending: false }).limit(100),
  ]);
  const byProduct = new Map<string, RecordValue>(); for (const result of results.data ?? []) if (!byProduct.has(String(result.catalog_product_id))) byProduct.set(String(result.catalog_product_id), result as RecordValue);
  const ai = getCatalogAiReadiness();
  return <main className="space-y-5">
    <section className="card"><span className="badge">REVIEW-ONLY · INTEGRACIONES EXTERNAS DESACTIVADAS</span><h1 className="mt-2 text-2xl font-bold">Catálogo externo</h1><p className="mt-2 text-sm">La IA está bloqueada en producción y solo genera propuestas internas cuando la configuración segura lo permite.</p><form action={runTestCatalogSyncAction} className="mt-4"><button className="btn" type="submit">Importar catálogo ficticio (5 productos)</button></form></section>
    <section className="card"><h2 className="text-lg font-bold">IA Gateway</h2><p className="mt-2 text-sm">Modo: {ai.mode}; entorno: {ai.environment}; habilitada: {ai.enabled ? "sí" : "no"}; razón: {ai.reason ?? "lista"}. No publica ni modifica la fuente original.</p></section>
    <section className="card"><h2 className="text-lg font-bold">Agregar proveedor</h2><form action={createCatalogSupplierAction} className="mt-3 grid gap-3 md:grid-cols-3"><input className="rounded border p-2" name="name" placeholder="Nombre" required /><select className="rounded border p-2" name="feedType" defaultValue="json"><option value="json">JSON</option><option value="csv">CSV</option><option value="xml">XML</option><option value="api">API REST</option><option value="url_feed">Feed URL</option></select><input className="rounded border p-2" name="feedUrl" placeholder="URL del feed (opcional)" type="url" /><button className="btn md:col-span-3" type="submit">Guardar proveedor en borrador</button></form></section>
    <section className="card overflow-x-auto"><h2 className="text-lg font-bold">Original del proveedor vs propuesta IA</h2>{(products.data ?? []).map((product) => { const supplier = (Array.isArray(product.supplier_products) ? product.supplier_products[0] : product.supplier_products) as RecordValue | null; const result = byProduct.get(String(product.id)); const output = result?.output as RecordValue | undefined; return <article className="mt-4 grid gap-4 border-t pt-4 lg:grid-cols-2" key={product.id}><div><h3 className="font-bold">Original del proveedor</h3><p><strong>{String(supplier?.original_title ?? product.title)}</strong></p><p className="text-sm">{String(supplier?.original_description ?? "Sin descripción")}</p><p className="text-sm">Marca: {String(supplier?.brand ?? "—")} · Categoría: {String(supplier?.category ?? "—")} · Costo: {product.cost ?? "—"} · Stock: {product.stock ?? "—"}</p></div><div><h3 className="font-bold">Propuesta IA</h3>{output ? <><p><strong>{String(output.title)}</strong></p><p className="text-sm">{String(output.description)}</p><p className="text-sm">SEO: {String(output.seo_title)} · Score: {String(output.quality_score)} · Recomendación: {String(output.recommendation)}</p><p className="text-sm">Razones: {Array.isArray(output.reasons) ? output.reasons.join(", ") : "—"}</p>{result?.status === "completed" ? <form action={reviewCatalogAiAction} className="mt-2 flex gap-2"><input name="resultId" type="hidden" value={String(result.id)} /><button className="btn" name="decision" value="approved" type="submit">Aprobar propuesta</button><button className="btn btn-secondary" name="decision" value="rejected" type="submit">Rechazar propuesta</button></form> : <p className="text-sm">Estado IA: {String(result?.status)}</p>}</> : <form action={processCatalogAiAction}><input name="catalogProductId" type="hidden" value={product.id} /><button className="btn mt-2" disabled={!ai.enabled} type="submit">Procesar con IA</button></form>}</div></article>; })}</section>
    <section className="card"><h2 className="text-lg font-bold">Proveedores</h2><ul>{(suppliers.data ?? []).map((supplier) => <li key={supplier.id}>{supplier.name} · {supplier.feed_type} · {supplier.status}</li>)}</ul></section>
  </main>;
}
