import Link from "next/link";
import { requireAdmin } from "@/lib/supabase/require-admin";
import { getCatalogAiReadiness } from "@/services/catalog-ai-service";
import { createCatalogSupplierAction, decideCatalogProductAction, runTestCatalogSyncAction } from "./actions";

export default async function CatalogControlPage() {
  const { supabase } = await requireAdmin();
  const [suppliers, products, runs, errors] = await Promise.all([
    supabase.from("suppliers").select("id,name,status,feed_type,last_sync_at").order("created_at", { ascending: false }).limit(20),
    supabase.from("catalog_products").select("id,title,status,price,cost,margin,stock,score,missing_fields,supplier_products(suppliers(name))").order("updated_at", { ascending: false }).limit(50),
    supabase.from("catalog_sync_runs").select("id,status,trigger_type,received_count,created_count,updated_count,error_count,started_at").order("started_at", { ascending: false }).limit(10),
    supabase.from("catalog_sync_errors").select("id,error_code,message,created_at").order("created_at", { ascending: false }).limit(10),
  ]);
  const ai = getCatalogAiReadiness();
  return <main className="space-y-5">
    <section className="card"><span className="badge">REVIEW-ONLY · SHOPIFY DISABLED</span><h1 className="mt-2 text-2xl font-bold">Catálogo externo</h1><p className="mt-2 text-sm">CSV, XML, JSON, API y feeds están preparados. Los conectores reales permanecen desactivados; no se guardan claves en navegador.</p><form action={runTestCatalogSyncAction} className="mt-4"><button className="btn" type="submit">Importar catálogo ficticio (5 productos)</button></form></section>
    <section className="card"><h2 className="text-lg font-bold">Agregar proveedor</h2><form action={createCatalogSupplierAction} className="mt-3 grid gap-3 md:grid-cols-3"><input className="rounded border p-2" name="name" placeholder="Nombre" required /><select className="rounded border p-2" name="feedType" defaultValue="json"><option value="json">JSON</option><option value="csv">CSV</option><option value="xml">XML</option><option value="api">API REST</option><option value="url_feed">Feed URL</option><option value="shopify">Shopify (futuro)</option></select><input className="rounded border p-2" name="feedUrl" placeholder="URL del feed (opcional)" type="url" /><button className="btn md:col-span-3" type="submit">Guardar proveedor en borrador</button></form></section>
    <section className="grid gap-4 md:grid-cols-3"><Metric label="Proveedores" value={suppliers.data?.length ?? 0} /><Metric label="Productos procesados" value={products.data?.length ?? 0} /><Metric label="Errores recientes" value={errors.data?.length ?? 0} /></section>
    <section className="card"><h2 className="text-lg font-bold">IA Gateway</h2><p className="mt-2 text-sm">Modo: {ai.mode}. Configurada: {ai.gatewayConfigured ? "sí" : "no"}. Habilitada: {ai.enabled ? "sí" : "no"}. Cualquier resultado requiere revisión y no altera precio, stock ni datos no presentes en la fuente.</p></section>
    <section className="card overflow-x-auto"><h2 className="text-lg font-bold">Proveedores</h2><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Nombre</th><th>Feed</th><th>Estado</th><th>Última sync</th></tr></thead><tbody>{(suppliers.data ?? []).map((supplier) => <tr className="border-t" key={supplier.id}><td className="p-2">{supplier.name}</td><td>{supplier.feed_type}</td><td>{supplier.status}</td><td>{supplier.last_sync_at ?? "Sin ejecutar"}</td></tr>)}</tbody></table></section>
    <section className="card overflow-x-auto"><h2 className="text-lg font-bold">Resultado del catálogo</h2><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Producto original / normalizado</th><th>Precio</th><th>Margen</th><th>Stock</th><th>Score</th><th>Decisión</th></tr></thead><tbody>{(products.data ?? []).map((product) => { const score = product.score as { total?: number; decision?: string } | null; return <tr className="border-t" key={product.id}><td className="p-2"><strong>{product.title}</strong><br /><span className="text-xs">Faltantes: {Array.isArray(product.missing_fields) && product.missing_fields.length ? product.missing_fields.join(", ") : "ninguno"}</span></td><td>{product.price ?? "—"}</td><td>{product.margin ?? "—"}%</td><td>{product.stock ?? "—"}</td><td>{score?.total ?? "—"}</td><td>{score?.decision ?? product.status}<form action={decideCatalogProductAction} className="mt-1 flex gap-1"><input name="id" type="hidden" value={product.id} /><button className="underline" name="decision" value="approved" type="submit">Aprobar</button><button className="underline" name="decision" value="rejected" type="submit">Rechazar</button></form></td></tr>; })}</tbody></table><p className="mt-3 text-sm"><Link href="/admin/autopilot/review">La aprobación humana existente sigue siendo obligatoria.</Link></p></section>
    <section className="card"><h2 className="text-lg font-bold">Ejecuciones y errores</h2><p className="mt-2 text-sm">Runs: {(runs.data ?? []).map((run) => `${run.status} (${run.created_count} creados, ${run.updated_count} actualizados, ${run.error_count} errores)`).join(" · ") || "Sin ejecuciones"}</p><ul className="mt-2 list-disc pl-5 text-sm">{(errors.data ?? []).map((error) => <li key={error.id}>{error.error_code}: {error.message}</li>)}</ul></section>
  </main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="card"><p className="text-sm text-gray-600">{label}</p><p className="text-3xl font-bold">{value}</p></div>; }
